USE [master]
GO
/****** Object:  Database [Progetto]    Script Date: 18/04/2024 10:56:55 ******/
CREATE DATABASE [Progetto]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Progetto', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\Progetto.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Progetto_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\Progetto_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [Progetto] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Progetto].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [Progetto] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [Progetto] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [Progetto] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [Progetto] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [Progetto] SET ARITHABORT OFF 
GO
ALTER DATABASE [Progetto] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [Progetto] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [Progetto] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [Progetto] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [Progetto] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [Progetto] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [Progetto] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [Progetto] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [Progetto] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [Progetto] SET  DISABLE_BROKER 
GO
ALTER DATABASE [Progetto] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [Progetto] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [Progetto] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [Progetto] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [Progetto] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [Progetto] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [Progetto] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [Progetto] SET RECOVERY FULL 
GO
ALTER DATABASE [Progetto] SET  MULTI_USER 
GO
ALTER DATABASE [Progetto] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [Progetto] SET DB_CHAINING OFF 
GO
ALTER DATABASE [Progetto] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [Progetto] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [Progetto] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [Progetto] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'Progetto', N'ON'
GO
ALTER DATABASE [Progetto] SET QUERY_STORE = ON
GO
ALTER DATABASE [Progetto] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [Progetto]
GO
/****** Object:  User [progetto]    Script Date: 18/04/2024 10:56:55 ******/
CREATE USER [progetto] FOR LOGIN [progetto] WITH DEFAULT_SCHEMA=[dbo]
GO
ALTER ROLE [db_owner] ADD MEMBER [progetto]
GO
/****** Object:  Table [dbo].[Prenotazioni]    Script Date: 18/04/2024 10:56:55 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Prenotazioni](
	[IdPrenotazione] [int] IDENTITY(1,1) NOT NULL,
	[IdRisorsa] [int] NOT NULL,
	[DataInizio] [date] NOT NULL,
	[DataFine] [date] NOT NULL,
 CONSTRAINT [PK_Prenotazioni] PRIMARY KEY CLUSTERED 
(
	[IdPrenotazione] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Risorse]    Script Date: 18/04/2024 10:56:55 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Risorse](
	[IdRisorsa] [int] NOT NULL,
	[Nome] [varchar](100) NOT NULL,
	[IdRisorsaTipologia] [int] NOT NULL,
 CONSTRAINT [PK_Risorse] PRIMARY KEY CLUSTERED 
(
	[IdRisorsa] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[RisorseTipologia]    Script Date: 18/04/2024 10:56:55 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[RisorseTipologia](
	[IdRisorsaTipologia] [int] NOT NULL,
	[NomeTipologia] [varchar](100) NOT NULL,
 CONSTRAINT [PK_RisorseTipologia] PRIMARY KEY CLUSTERED 
(
	[IdRisorsaTipologia] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Utenti]    Script Date: 18/04/2024 10:56:55 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Utenti](
	[IdUtente] [int] IDENTITY(1,1) NOT NULL,
	[Email] [varchar](100) NOT NULL,
	[Nome] [varchar](100) NOT NULL,
	[Cognome] [varchar](100) NOT NULL,
	[Password] [varchar](100) NOT NULL,
 CONSTRAINT [PK_Utenti] PRIMARY KEY CLUSTERED 
(
	[IdUtente] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Prenotazioni]  WITH CHECK ADD  CONSTRAINT [FK_Prenotazioni_Risorse] FOREIGN KEY([IdRisorsa])
REFERENCES [dbo].[Risorse] ([IdRisorsa])
GO
ALTER TABLE [dbo].[Prenotazioni] CHECK CONSTRAINT [FK_Prenotazioni_Risorse]
GO
ALTER TABLE [dbo].[Risorse]  WITH CHECK ADD  CONSTRAINT [FK_Risorse_RisorseTipologia] FOREIGN KEY([IdRisorsaTipologia])
REFERENCES [dbo].[RisorseTipologia] ([IdRisorsaTipologia])
GO
ALTER TABLE [dbo].[Risorse] CHECK CONSTRAINT [FK_Risorse_RisorseTipologia]
GO
USE [master]
GO
ALTER DATABASE [Progetto] SET  READ_WRITE 
GO
